apiVersion: v1
kind: Service
metadata:
  name: giribabu-micro
  namespace: giribabu
spec:
  selector:
    app: giribabu-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
